### ISSUE TITLE
tar.gz archives are not extracted correctly

### ISSUE THREAD

**Issue by berggren** [openrelik/openrelik-worker-extraction#6]
When extracting a tar.gz archive the output is the tar file. I expect the output to be the content of the unzipped tar archive.

<img width="673" alt="Screenshot 2024-10-16 at 11 39 20" src="https://github.com/user-attachments/assets/3317236f-0bcb-4f27-9c6e-a09bf845d94d">

**Comment by hacktobeer** [comment]
I'll have loook at this. I suspect 7zip treats it as 1 archive and 1 compression so when given the .tar.gz file it will only decompress the first one and not continue with unpacking the archive. The tar.gz format is strange as it is indeed 2 seperate archive containers.
